Etapa 1 - hasta service discovery
fbusso/dan-trabajo-practico pull request #12
Opened 2021-08-18 22:04 UTC by GiovaniFerraroTrivelli

2021-08-18 22:10 UTC, fbusso requested changes

2021-08-18 22:10 UTC, fbusso commented on src/usuario/src/main/resources/application.properties
> +eureka.client.serviceUrl.defaultZone=http://localhost:8082/eureka
Parametrizar (Ver `application.properties` de microservicio de cuenta)

2021-08-18 22:10 UTC, fbusso commented on src/pedido/src/main/resources/db/migration/V1__EntidadesMicroservicioPedido.sql
> +    descripcion VARCHAR(100)   NOT NULL
Crear un nuevo script de Migración que elimine la columna. Esa es la forma correcta de hacerlo en flyway, sino se rompe la suma de verificación del schema.

2021-08-18 22:13 UTC, GiovaniFerraroTrivelli commented on src/pedido/src/main/resources/db/migration/V1__EntidadesMicroservicioPedido.sql
> +    descripcion VARCHAR(100)   NOT NULL
@BodeMatias

2021-08-18 22:18 UTC, fbusso commented
- Agregar `Dockerfile` para los servicios agregados. Revisar estructura de los otros microservicios.
- Agregar servicios nuevos al `docker-compose.yml`.
- Agregar linea para buildear los microservicios agregados a los archivos `build.sh` y `build.ps1`

2021-08-19 03:02 UTC, fbusso approved these changes

2021-08-19 03:02 UTC, merged